server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ht123abc*#
  application:
    name: orderservice

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

mybatis-plus:
  mapper-locations: classpath*:com/example/**/*Mapper.xml
  type-aliases-package: com.example.*.pojo
  global-config:
    db-config:
      id-type: assign_uuid
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql

logging:
  level:
    com.example.orderservice: debug

userservice:
  riddon:
    listOfServers: localhost:8081,localhost:8082