server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: orderservice
  loadbalancer:
    eager-load:
      clients:
        - userservice
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
        group: DEFAULT_GROUP
        namespace: f1991878-106a-488b-b275-e42f11e408c9
        ephemeral: false

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka

mybatis-plus:
  mapper-locations: classpath*:com/example/**/*Mapper.xml
  type-aliases-package: com.example.*.pojo
  global-config:
    db-config:
      id-type: assign_uuid
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql

logging:
  level:
    com.example.orderservice: debug
    org.springframework.cloud: debug

# 不能使用生产中需要维护IP
#userservice:
#  riddon:
#    listOfServers: localhost:8081,localhost:8082

# 测试Env
my:
  config: 1