server:
  port: 8080
spring:
  application:
    name: orderservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.119.128:3306/cloud-order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      username: nacos
      password: nacos
      server-addr: 192.168.119.128:8848
      discovery:
        cluster-name: HZ
        group: DEFAULT_GROUP
        #namespace: f1991878-106a-488b-b275-e42f11e408c9
        ephemeral: false
    loadbalancer:
      eager-load:
        clients:
          - userservice
    openfeign:
      httpclient:
        enabled: true
        max-connections: 200
        max-connections-per-route: 50 # 每个路径最大连接数
    #      client:
    #        config:
    #          default:
    #            logger-level: FULL
    sentinel:
      transport:
        dashboard: localhost:1011
      web-context-unify: false
      datasource:
        flow:
          nacos:
            server-addr: 192.168.119.128:8848
            username: nacos
            password: nacos
            data-id: orderservice-flow-rules
            group-id: SENTINEL_GROUP
            rule-type: flow

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
#    allow-redirects: true

feign:
  sentinel:
    enabled: true

seata:
  registry:
    type: nacos
    nacos:
  tx-service-group:

mybatis-plus:
  mapper-locations: classpath*:com/example/**/*Mapper.xml
  type-aliases-package: com.example.*.pojo
  global-config:
    db-config:
      id-type: assign_uuid
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql

logging:
  level:
    com.example.orderservice: debug
    org.springframework.cloud: debug
    com.alibaba.*: debug

# 不能使用生产中需要维护IP
#userservice:
#  riddon:
#    listOfServers: localhost:8081,localhost:8082

# 测试Env
my:
  config: 1