server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.119.128:3306/cloud-user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: userservice
  cloud:
    nacos:
      server-addr: 192.168.119.128:8848
      discovery:
        cluster-name: HZ

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka

mybatis-plus:
  mapper-locations: classpath*:com/example/**/*Mapper.xml
  type-aliases-package: com.example.*.pojo
  global-config:
    db-config:
      id-type: assign_uuid
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql

logging:
  level:
    com.example.userservice: debug