spring:
  rabbitmq:
    host: 192.168.119.128
    port: 5672
    username: rabbit
    password: rabbit
    virtual-host: /

logging:
  level:
    com.*: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss