spring:
  rabbitmq:
    host: 192.168.16.101
    port: 5672
    username: rabbit
    password: rabbit
    virtual-host: /
    listener:
      simple:
        prefetch: 1
logging:
  level:
    com.*: debug