server:
  port: 8099
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ht123abc*#
  rabbitmq:
    host: 192.168.16.101
    port: 5672
    username: rabbit
    password: rabbit
    virtual-host: /
logging:
  level:
    com.*: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

mybatis-plus:
  mapper-locations: classpath*:com/example/**/*Mapper.xml
  type-aliases-package: com.example.*.pojo
  global-config:
    db-config:
      id-type: assign_uuid
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: mysql