server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
    gateway:
      routes:
      - id: user-service
        uri: lb://userservice
        predicates:
        - Path=/user/**
      - id: order-service
        uri: lb://orderservice
        predicates:
        - Path=/order/**
        - Before=2023-06-28T17:42:47.789-08:00[Asia/Shanghai]
