server:
  port: 10086
spring:
  application:
    name: eurekaservice
  cloud:
    loadbalancer:
      enabled: true #默认true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
